
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 26 13:17:41 CET 2015
//----------------------------------------------------

package email;

/** CUP generated interface containing symbol constants. */
public interface EmailSym {
  /* terminals */
  public static final int TERM = 2;
  public static final int SEND = 3;
  public static final int EMAIL = 8;
  public static final int INBOX = 7;
  public static final int ADDTOSPAM = 5;
  public static final int EOF = 0;
  public static final int REMOVEFROMSPAM = 6;
  public static final int error = 1;
  public static final int RECIEVE = 4;
}

